id: DC2FF0805
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:50:40+00:00'
last_modified: '2022-05-29T08:37:20.497976+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '7005':
      image_group_id: I1PD95922
      title: ལས་གྲུབ་པའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1517
      order: 77
      base_file: 7005.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
