id: PE04C9A87
initial_creation_type: ocr
source_metadata:
  volumes:
    2543fb54888c4a899d236bdcef1a2be6:
      base_file: v077.txt
      image_group_id: I1PD95922
      title: ལས་གྲུབ་པའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1517
      volume_number: 77
